services:
  resource-service:
    container_name: resource-service-container
    build: resource-service/
    ports: 
      - "8080:8080"
    depends_on: 
      - resource-db
      - eureka-service-discovery
  
  resource-db:
    container_name: resource-db-container
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=resources
    volumes:
      - ./resource-service/db_docker:/docker-entrypoint-initdb.d/

  song-service-1:
    container_name: song-service-container-1
    build: song-service/
    ports:
      - "8085:8080"
    depends_on:
      - song-db
      - eureka-service-discovery

  song-service-2:
    container_name: song-service-container-2
    build: song-service/
    ports:
      - "8086:8080"
    depends_on:
      - song-db
      - eureka-service-discovery

  song-db:
    container_name: song-db-container
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=songs
    volumes:
      - ./song-service/db_docker:/docker-entrypoint-initdb.d/

  eureka-service-discovery:
    container_name: eureka-service-discovery-container
    build: eureka-service-discovery/
    ports:
      - "8761:8761"
